version: '2'
services:
  dbpostgres:
    image: postgres:9.6
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql/data
      - ./docker/scripts/startup-script.sh:/docker-entrypoint-initdb.d/startup-script.sh
      - ./docker/scripts/tl.dmp:/tl.dmp
    ports:
      - "5777:5432"
    environment:
      POSTGRES_PASSWORD: stearmanPT-17
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres